# Generated by Django 4.2 on 2023-05-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='CodingSkills',
        ),
        migrations.RenameModel(
            old_name='Tool',
            new_name='Tools',
        ),
    ]
