# Generated by Django 4.2 on 2023-05-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0002_rename_skill_codingskills_rename_tool_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingSkills',
            new_name='CodingSkill',
        ),
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
