# Generated by Django 4.2 on 2023-05-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0003_rename_codingskills_codingskill_rename_tools_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('roles_responsibility', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('close', 'Close')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coding_skills_used', models.ManyToManyField(related_name='projects', to='resume_generator.codingskill')),
                ('tools_used', models.ManyToManyField(related_name='projects', to='resume_generator.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_status', models.CharField(choices=[('current', 'Current'), ('ex', 'Ex')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coding_skills', models.ManyToManyField(to='resume_generator.codingskill')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.designation')),
                ('tools', models.ManyToManyField(to='resume_generator.tool')),
            ],
        ),
    ]
