# Generated by Django 4.2 on 2023-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0005_remove_project_coding_skills_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
