# Generated by Django 4.2 on 2023-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0009_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('close', 'Closed')], default='active', max_length=10),
        ),
    ]
