# Generated by Django 4.2 on 2023-05-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0011_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
