# Generated by Django 4.2 on 2023-05-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0012_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('professional_summary', models.TextField()),
                ('employee_status', models.CharField(choices=[('current', 'Current'), ('ex', 'Ex')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coding_skills', models.ManyToManyField(to='resume_generator.codingskill')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.designation')),
                ('tools', models.ManyToManyField(to='resume_generator.tool')),
            ],
        ),
    ]
