# Generated by Django 4.2 on 2023-05-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0013_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_status',
            new_name='employment_status',
        ),
    ]
