# Generated by Django 4.2 on 2023-05-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0014_rename_employee_status_employee_employment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_generator.project')),
            ],
        ),
    ]
