# Generated by Django 4.2 on 2023-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0015_employeeprojectmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(to='resume_generator.project'),
        ),
        migrations.DeleteModel(
            name='EmployeeProjectMapping',
        ),
    ]
